// ─────────────────────────────────────────────────────────────
// THE ROBI PROJECT — content registry
// Parts carry the Robi intelligence layer shown in callouts,
// holo cards and the component explorer.
// ─────────────────────────────────────────────────────────────

export const PARTS = {
  visor: {
    name: 'Head sensor array',
    code: 'SNS-01',
    cat: 'sensors',
    type: 'Multi-spectral perception visor',
    role: 'Primary vision band fusing RGB, IR and event cameras for scene understanding.',
    supplier: 'Perception hardware suppliers',
    verified: 34,
    price: '$2.1k – $7.8k',
    lead: '6–10 wks',
    comp: 'CE · RoHS · IEC 62471',
    risk: 'Firmware lock-in on two market leaders',
    alts: '3 validated alternates',
  },
  depth_cam: {
    name: 'Depth camera',
    code: 'SNS-02',
    cat: 'sensors',
    type: 'Active stereo depth module',
    role: 'Millimetre-grade depth for grasping, navigation and human detection.',
    supplier: 'Depth & 3D vision vendors',
    verified: 41,
    price: '$180 – $1.4k',
    lead: '2–6 wks',
    comp: 'CE · FCC · Class 1 laser',
    risk: 'Frequent EOL cycles — pin revisions',
    alts: '5 validated alternates',
  },
  lidar: {
    name: 'LiDAR',
    code: 'SNS-03',
    cat: 'sensors',
    type: 'Solid-state 360° LiDAR puck',
    role: 'Long-range mapping and safety-rated obstacle detection.',
    supplier: 'LiDAR manufacturers',
    verified: 22,
    price: '$450 – $6.2k',
    lead: '4–12 wks',
    comp: 'CE · IEC 60825-1',
    risk: 'Export-control review for two origins',
    alts: '4 validated alternates',
  },
  mics: {
    name: 'Microphone array',
    code: 'SNS-04',
    cat: 'sensors',
    type: '6-element beamforming array',
    role: 'Voice command capture and acoustic event detection on the floor.',
    supplier: 'Acoustic component suppliers',
    verified: 28,
    price: '$40 – $320',
    lead: '1–4 wks',
    comp: 'CE · RoHS',
    risk: 'Low — commodity class',
    alts: '6 validated alternates',
  },
  shoulder_act: {
    name: 'Shoulder actuator',
    code: 'ACT-01',
    cat: 'actuation',
    type: 'QDD torque actuator · 120 Nm',
    role: 'High-torque quasi-direct-drive unit powering the arm’s primary axes.',
    supplier: 'Actuator & servo suppliers',
    verified: 47,
    price: '$1.8k – $5.4k',
    lead: '8–16 wks',
    comp: 'CE · ISO 9409 flange',
    risk: 'Two suppliers hold ~70% of capacity',
    alts: '4 validated alternates',
  },
  elbow: {
    name: 'Elbow joint',
    code: 'ACT-02',
    cat: 'actuation',
    type: 'Harmonic-drive joint module · 60 Nm',
    role: 'Mid-arm articulation with integrated encoder and brake.',
    supplier: 'Joint module suppliers',
    verified: 39,
    price: '$950 – $3.2k',
    lead: '6–12 wks',
    comp: 'CE · RoHS',
    risk: 'Gearbox tariff exposure in 2 regions',
    alts: '5 validated alternates',
  },
  motor_ctrl: {
    name: 'Motor controller',
    code: 'ACT-03',
    cat: 'actuation',
    type: 'FOC servo drive · 48 V / 40 A',
    role: 'Field-oriented control electronics driving each actuator cluster.',
    supplier: 'Drive electronics vendors',
    verified: 52,
    price: '$210 – $890',
    lead: '3–8 wks',
    comp: 'CE · UL 61800',
    risk: 'MCU allocation watch (Q3)',
    alts: '7 validated alternates',
  },
  hand: {
    name: 'Robotic hand',
    code: 'MAN-01',
    cat: 'manipulation',
    type: '16-DoF dexterous hand',
    role: 'Human-scale grasping with per-finger force control and tactile pads.',
    supplier: 'Dexterous end-effector suppliers',
    verified: 18,
    price: '$6.5k – $28k',
    lead: '10–20 wks',
    comp: 'CE · ISO/TS 15066 contact limits',
    risk: 'Highest-variance quotes in the BoM',
    alts: '3 validated alternates',
  },
  torque_sensor: {
    name: 'Torque sensor',
    code: 'MAN-02',
    cat: 'manipulation',
    type: '6-axis wrist F/T sensor',
    role: 'Force-torque sensing for compliant contact and safe hand-offs.',
    supplier: 'Force sensing specialists',
    verified: 26,
    price: '$1.2k – $4.6k',
    lead: '5–10 wks',
    comp: 'CE · IP65',
    risk: 'Calibration service is single-region',
    alts: '4 validated alternates',
  },
  battery: {
    name: 'Battery pack',
    code: 'PWR-01',
    cat: 'power',
    type: '52 V Li-ion pack · 2.2 kWh',
    role: 'Swappable energy module rated for 4–6 h duty cycles.',
    supplier: 'Battery pack integrators',
    verified: 31,
    price: '$2.4k – $8.9k',
    lead: '6–14 wks',
    comp: 'UN 38.3 · IEC 62133 · UL 2271',
    risk: 'Dangerous-goods shipping lanes vary',
    alts: '3 validated alternates',
  },
  bms: {
    name: 'BMS',
    code: 'PWR-02',
    cat: 'power',
    type: 'Battery management system',
    role: 'Cell balancing, thermal watch and safe-state cutoff for the pack.',
    supplier: 'BMS electronics vendors',
    verified: 36,
    price: '$180 – $760',
    lead: '3–7 wks',
    comp: 'CE · ISO 26262-informed',
    risk: 'Firmware audit needed on 1 vendor',
    alts: '5 validated alternates',
  },
  charger: {
    name: 'Charging unit',
    code: 'PWR-03',
    cat: 'power',
    type: 'Dock + onboard charge interface',
    role: 'Autonomous docking and 1.5 kW fast-charge with fleet scheduling.',
    supplier: 'Charging infrastructure suppliers',
    verified: 24,
    price: '$900 – $3.8k',
    lead: '4–9 wks',
    comp: 'CE · UL 62368',
    risk: 'Site electrical permits add lead time',
    alts: '3 validated alternates',
  },
  compute: {
    name: 'Edge compute unit',
    code: 'CMP-01',
    cat: 'compute',
    type: 'Edge AI module · 275 TOPS',
    role: 'Runs perception, planning and control loops fully on-board.',
    supplier: 'Edge compute vendors',
    verified: 29,
    price: '$1.1k – $4.2k',
    lead: '4–10 wks',
    comp: 'CE · FCC · IEC 62368',
    risk: 'GPU allocation cycles — reserve early',
    alts: '3 validated alternates',
  },
  harness: {
    name: 'Wiring harness',
    code: 'INT-01',
    cat: 'integration',
    type: 'Power + data trunk harness',
    role: 'Shielded backbone routing 48 V power and EtherCAT through every joint.',
    supplier: 'Harness & cable fabricators',
    verified: 44,
    price: '$350 – $1.9k',
    lead: '3–8 wks',
    comp: 'UL 758 · RoHS',
    risk: 'Drawing revisions drive most delays',
    alts: '6 validated alternates',
  },
  hip: {
    name: 'Hip assembly',
    code: 'MOB-01',
    cat: 'mobility',
    type: '3-DoF hip module',
    role: 'Pelvis-mounted actuator stack that carries the full upper-body load.',
    supplier: 'Locomotion subsystem suppliers',
    verified: 21,
    price: '$4.2k – $11k',
    lead: '10–18 wks',
    comp: 'CE · fatigue-test dossier',
    risk: 'Casting capacity is the bottleneck',
    alts: '2 validated alternates',
  },
  knee: {
    name: 'Knee actuator',
    code: 'MOB-02',
    cat: 'mobility',
    type: 'High-torque knee unit · 200 Nm',
    role: 'Peak-load joint for squat, lift and stair profiles.',
    supplier: 'Actuator & servo suppliers',
    verified: 33,
    price: '$2.2k – $6.8k',
    lead: '8–14 wks',
    comp: 'CE · ISO 10218-informed',
    risk: 'Thermal derating varies by vendor',
    alts: '4 validated alternates',
  },
  foot_sensor: {
    name: 'Foot pressure sensor',
    code: 'MOB-03',
    cat: 'mobility',
    type: 'Plantar pressure matrix',
    role: 'Ground-contact sensing for balance, gait and slip detection.',
    supplier: 'Tactile sensing suppliers',
    verified: 19,
    price: '$220 – $980',
    lead: '3–6 wks',
    comp: 'CE · IP54',
    risk: 'Wear-part — plan consumable stock',
    alts: '4 validated alternates',
  },
  estop: {
    name: 'Emergency-stop system',
    code: 'SAF-01',
    cat: 'safety',
    type: 'Cat. 3 safe-stop chain',
    role: 'Hardwired e-stop, wireless kill switch and safe-torque-off path.',
    supplier: 'Safety component suppliers',
    verified: 27,
    price: '$340 – $1.6k',
    lead: '2–6 wks',
    comp: 'ISO 13850 · PLd Cat. 3',
    risk: 'Site audit required before go-live',
    alts: '4 validated alternates',
  },
  frame: {
    name: 'Structural frame',
    code: 'INT-02',
    cat: 'integration',
    type: 'Torso + limb structural set',
    role: 'Machined aluminium and carbon shells that everything else bolts into.',
    supplier: 'Fabrication & CM partners',
    verified: 58,
    price: '$3.8k – $14k',
    lead: '6–12 wks',
    comp: 'Material certs · CMM report',
    risk: 'Tolerance stack-ups on rev changes',
    alts: '8 validated partners',
  },
};

// ─── Scroll dissection stages ────────────────────────────────
export const STAGES = [
  {
    id: 'overview',
    num: '00',
    kicker: 'The humanoid · assembled',
    title: 'One machine. Hundreds of sourcing decisions.',
    what: 'A production humanoid integrates 18+ major subsystems from dozens of specialist suppliers.',
    why: 'Robbie reads the whole machine — then helps you buy every part of it with confidence.',
    robbie: 'Keep scrolling. I’ll dissect the platform system by system.',
    parts: [],
    featured: null,
    view: { f: 0.04, zoom: 1.0,  cx: 0.5,   cy: 0.5 },
    marks: [],
  },
  {
    id: 'sensors',
    num: '01',
    kicker: 'Category · Sensors',
    title: 'Perception is the spec sheet that matters.',
    what: 'Vision, depth, LiDAR and audio are the humanoid’s window into your facility.',
    why: 'Sensor choice drives autonomy performance, safety certification and BoM cost more than any other subsystem.',
    robbie: 'Robbie helps you discover and compare sensor suppliers.',
    parts: ['visor', 'depth_cam', 'lidar', 'mics'],
    featured: 'depth_cam',
    view: { f: 0.42, zoom: 1.45, cx: 0.5,   cy: 0.18 },
    marks: [['visor',0.5,0.062],['depth_cam',0.5,0.1],['lidar',0.505,0.035],['mics',0.552,0.078]],
  },
  {
    id: 'actuation',
    num: '02',
    kicker: 'Category · Actuation',
    title: 'The muscles are the biggest line item.',
    what: 'Torque-dense actuators, joint modules and drive electronics power 28+ axes of motion.',
    why: 'Actuation is the largest cost block in a humanoid — and carries the longest lead times.',
    robbie: 'Robbie helps you evaluate actuator suppliers by cost, lead time, and reliability.',
    parts: ['shoulder_act', 'elbow', 'motor_ctrl', 'arm_struct'],
    featured: 'shoulder_act',
    view: { f: 0.48, zoom: 1.55, cx: 0.62,  cy: 0.3 },
    marks: [['shoulder_act',0.552,0.28],['elbow',0.655,0.315],['motor_ctrl',0.558,0.345],['arm_struct',0.315,0.325]],
  },
  {
    id: 'power',
    num: '03',
    kicker: 'Category · Power',
    title: 'Runtime is a procurement decision.',
    what: 'A high-density battery pack, its BMS and the charging loop define the duty cycle.',
    why: 'Certification, thermal limits and dangerous-goods logistics all hang off the pack you choose.',
    robbie: 'Robbie helps you review battery options, compliance, and lifecycle cost.',
    parts: ['battery', 'bms', 'charger'],
    featured: 'battery',
    view: { f: 0.53, zoom: 1.7,  cx: 0.5,   cy: 0.42 },
    marks: [['battery',0.498,0.44],['bms',0.527,0.395],['charger',0.468,0.51]],
  },
  {
    id: 'compute',
    num: '04',
    kicker: 'Category · Compute',
    title: 'The brain locks in your stack.',
    what: 'Edge compute runs perception, planning and control loops entirely on-board.',
    why: 'Compute choice fixes your software ecosystem, thermal envelope and upgrade path for years.',
    robbie: 'Robbie helps you assess compute vendors, integration fit, and deployment readiness.',
    parts: ['compute', 'motor_ctrl'],
    featured: 'compute',
    view: { f: 0.58, zoom: 1.75, cx: 0.5,   cy: 0.3 },
    marks: [['compute',0.5,0.315],['motor_ctrl',0.44,0.345]],
  },
  {
    id: 'manipulation',
    num: '05',
    kicker: 'Category · Manipulation',
    title: 'Hands decide what work gets done.',
    what: 'Dexterous hands, wrists and force-torque sensing turn motion into useful tasks.',
    why: 'Grasp reliability defines which workflows you can automate — and hands are the most quoted item on any humanoid BoM.',
    robbie: 'Robbie helps you compare dexterous hand suppliers and quote structures.',
    parts: ['hand', 'torque_sensor'],
    featured: 'hand',
    view: { f: 0.64, zoom: 1.75, cx: 0.68,  cy: 0.35 },
    marks: [['hand',0.735,0.36],['torque_sensor',0.706,0.342]],
  },
  {
    id: 'mobility',
    num: '06',
    kicker: 'Category · Mobility',
    title: 'Legs are logistics.',
    what: 'Hip assemblies, knee actuators and foot sensing keep the platform stable on real floors.',
    why: 'Gait-proven mechanics decide where the humanoid can actually work — and spares strategy decides if it keeps working.',
    robbie: 'Robbie helps you benchmark locomotion suppliers, gait-proven assemblies, and spare-part programs.',
    parts: ['hip', 'knee', 'foot_sensor', 'leg_struct'],
    featured: 'hip',
    view: { f: 0.72, zoom: 1.5,  cx: 0.5,   cy: 0.72 },
    marks: [['hip',0.532,0.585],['knee',0.53,0.74],['foot_sensor',0.462,0.955],['leg_struct',0.568,0.71]],
  },
  {
    id: 'safety',
    num: '07',
    kicker: 'Category · Safety',
    title: 'Safety hardware is your deployment gate.',
    what: 'E-stop chains, safe-torque paths and contact-force limits protect the people beside the robot.',
    why: 'No pilot goes live without a conformity file — safety systems are the last gate before deployment.',
    robbie: 'Robbie helps you validate safety systems against CE, ISO 10218, and your site’s requirements.',
    parts: ['estop', 'torque_sensor', 'foot_sensor', 'bms'],
    featured: 'estop',
    view: { f: 0.8,  zoom: 1.5,  cx: 0.47,  cy: 0.36 },
    marks: [['estop',0.415,0.29],['torque_sensor',0.706,0.342],['foot_sensor',0.535,0.955],['bms',0.527,0.395]],
  },
  {
    id: 'integration',
    num: '08',
    kicker: 'Category · Integration',
    title: 'Parts don’t ship a robot. Integration does.',
    what: 'The frame, wiring harness and interfaces turn a parts list into one working machine.',
    why: 'Integration is where budgets slip — fabrication, cabling and assembly partners make or break the timeline.',
    robbie: 'Robbie helps you find fabrication partners, contract manufacturers, and subsystem suppliers.',
    parts: ['harness', 'frame', 'charger', 'hip'],
    featured: 'harness',
    view: { f: 0.97, zoom: 1.0,  cx: 0.5,   cy: 0.5 },
    marks: [['harness',0.535,0.49],['frame',0.5,0.55],['charger',0.468,0.51],['hip',0.532,0.585]],
  },
];

// pseudo-parts that exist as geometry groups but borrow intel entries
export const PSEUDO_PARTS = {
  arm_struct: {
    name: 'Arm structure',
    code: 'ACT-04',
    cat: 'actuation',
    type: 'Upper-arm + forearm shells',
    role: 'Carbon-shelled structural links between the arm’s joint modules.',
    supplier: 'Fabrication & CM partners',
    verified: 58,
    price: '$800 – $2.6k',
    lead: '4–8 wks',
    comp: 'Material certs',
    risk: 'Low — multi-source',
    alts: '8 validated partners',
  },
  leg_struct: {
    name: 'Leg structure',
    code: 'MOB-04',
    cat: 'mobility',
    type: 'Femur + tibia structural links',
    role: 'Load-bearing machined links between hip, knee and ankle.',
    supplier: 'Fabrication & CM partners',
    verified: 58,
    price: '$1.2k – $3.4k',
    lead: '4–9 wks',
    comp: 'Material certs · fatigue data',
    risk: 'Low — multi-source',
    alts: '8 validated partners',
  },
};

export const ALL_PARTS = { ...PARTS, ...PSEUDO_PARTS };

export const CATEGORY_LABELS = {
  sensors: 'Sensors',
  actuation: 'Actuation',
  power: 'Power',
  compute: 'Compute',
  manipulation: 'Manipulation',
  mobility: 'Mobility',
  safety: 'Safety',
  integration: 'Integration',
};

// ─── RFQ Journey (pinned scroll section) ─────────────────────
export const FLOW = [
  ['Upload the BoM', 'Drag in PDFs, XLSX, CAD exports — Robbie securely extracts and analyzes your documents.'],
  ['Extract & cross-reference', 'Parts, quantities and key attributes identified, then matched against specs, drawings and datasheets.'],
  ['AI validation', 'Component compatibility analyzed, risks flagged, missing fields clarified before sourcing.'],
  ['Supplier discovery', 'Trust-scored suppliers researched per component — trust vs cost, region and risk on one view.'],
  ['Supplier outreach', 'RFQs issued to the shortlist and chased automatically until quotes land.'],
  ['Quote comparison', 'Every offer normalized to true landed cost and ranked against the trust graph.'],
  ['Financing & terms', 'Payment structures, leasing and terms modeled and pre-negotiated.'],
  ['Contract closure', 'Robbie carries the deal all the way to signature.'],
  ['Deployment', 'Parts land, spares are stocked — your robot goes to work.'],
];

// ─── Modules grid ────────────────────────────────────────────
export const MODULES = [
  ['Humanoid Requirement Builder', 'Turn a plain-language use case into an engineering-grade requirement spec.', 'target'],
  ['Smart BoM Intelligence', 'Upload or generate a BoM — every line matched, priced and risk-scored.', 'list'],
  ['Supplier Discovery', 'Search 3,200+ mapped robotics suppliers by component, region and capacity.', 'radar'],
  ['Supplier Trust Graph', 'Delivery history, certifications and references — scored on one graph.', 'graph'],
  ['RFQ Automation', 'Component-aware RFQs generated, issued and chased automatically.', 'send'],
  ['Quote Comparison', 'Landed cost, lead time and warranty normalized across every quote.', 'scales'],
  ['Compliance Vault', 'CE, ISO 10218, ISO/TS 15066, UN 38.3 — tracked per part, per site.', 'shield'],
  ['Financing & Leasing', 'Capex, lease and robots-as-a-service offers modeled side by side.', 'coins'],
  ['Contract Readiness', 'Benchmark terms, SLAs and IP clauses before you sign.', 'doc'],
  ['Deployment Planning', 'Site prep, safety audit, spares and training on one timeline.', 'rocket'],
];

// ─── FAQ ─────────────────────────────────────────────────────
export const FAQ = [
  [
    'What is Hello Robbie?',
    'Hello Robbie is the autonomous procurement OS built strictly for robotics supply chains. Robbie finds the best suppliers and manages your procurement end-to-end — extraction, validation, discovery, outreach, financing and contract closure — so you spend less time hunting for suppliers and more time iterating.',
  ],
  [
    'Can I explore a humanoid part by part?',
    'Yes. The interactive anatomy view dissects a reference humanoid into its major systems — sensors, actuation, power, compute, manipulation, mobility, safety and integration — and shows verified supplier intelligence for each part.',
  ],
  [
    'Can Robbie help me find suppliers for specific components?',
    'That’s Robbie’s core job. Ask for “dexterous hands under $15k with CE files” or “knee actuators, 200 Nm, EU-based” and Robbie returns verified suppliers with price bands, lead times and risk signals.',
  ],
  [
    'Can I upload an existing BoM?',
    'Yes. Smart BoM Intake accepts CSV, Excel and CAD-exported BoMs. Every line is matched to known components, priced against market data and flagged for compliance gaps or single-source risk.',
  ],
  [
    'Can Robbie compare quotes across suppliers?',
    'Quote Comparison normalizes every offer — unit price, tooling, shipping, duties, warranty and payment terms — into one landed-cost view, then scores each quote against the Supplier Trust Graph.',
  ],
  [
    'Can it support compliance and financing?',
    'The Compliance Vault tracks certifications per component and per deployment site, while the Financing Layer models purchase, leasing and robots-as-a-service structures from vetted financing partners.',
  ],
  [
    'Can it help with deployment planning?',
    'Deployment Readiness builds your go-live plan: site preparation, safety audits, charging infrastructure, spare-part strategy and operator training — all sequenced on one timeline.',
  ],
  [
    'Is this only for full humanoid robots?',
    'No. Teams use Hello Robbie to source individual subsystems — a gripper, a battery pack, a sensor suite — or to run full-platform procurement programs. Every module works at both scales.',
  ],
];

// ─── Logos ───────────────────────────────────────────────────
export const LOGOS = [
  'NORDWERK Automation',
  'Atlas Fulfilment Group',
  'Kestrel Robotics Lab',
  'Meridian Advanced Mfg.',
  'Havenport Logistics',
  'Vantor Systems',
  'ORU Dynamics',
  'Bluefield Research',
];
